name: indoor_location
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.0.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # 버젼 확인 필요
  permission_handler: ^8.1.4+2

  json_serializable: ^6.7.0
  time_machine: ^0.9.17

  flutter_mobx: ^2.0.6+5
  mobx: ^2.2.0
  mobx_codegen: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.4

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
